import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import HomeContent from "./routes/HomeContent";
import SearchContent from "./routes/SearchContent";
import { useState } from "react";
import Layout from "@/components/Layout";

const Home = () => {
  const [route, setroute] = useState<string>("Home");
  let component: React.ReactNode = <HomeContent />;

  if (route === "Home") {
    component = <HomeContent />;
  } else if (route === "Search") {
    component = <SearchContent />;
  }

  return (
    <div>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar state={route} setstate={setroute} />
        <Layout children={component} />
      </header>
    </div>
  );
};

export default Home;
